### ISSUE TITLE
Server error when placing a tower

### ISSUE THREAD

**Issue by danielmoniz** [danielmoniz/tower-defense#21]
(need to reproduce)

Error log:

placing tower at: 40 300
2017-12-18T20:22:45.076006+00:00 app[web.1]: /app/build/server/socketListeners.js:10
2017-12-18T20:22:45.076007+00:00 app[web.1]:     socket.gameManager.game.placeTower(tower);
2017-12-18T20:22:45.076008+00:00 app[web.1]:                        ^
2017-12-18T20:22:45.076009+00:00 app[web.1]: 
2017-12-18T20:22:45.076010+00:00 app[web.1]: TypeError: Cannot read property 'game' of undefined
2017-12-18T20:22:45.076012+00:00 app[web.1]:     at Socket.<anonymous> (/app/build/server/socketListeners.js:10:24)
2017-12-18T20:22:45.076012+00:00 app[web.1]:     at emitOne (events.js:116:13)
2017-12-18T20:22:45.076013+00:00 app[web.1]:     at Socket.emit (events.js:211:7)
2017-12-18T20:22:45.076013+00:00 app[web.1]:     at /app/node_modules/socket.io/lib/socket.js:513:12
2017-12-18T20:22:45.076014+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2017-12-18T20:22:45.076015+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
2017-12-18T20:22:44.979575+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=M1hIizg" host=tower-defense-mobx.herokuapp.com request_id=618762da-e211-4322-b98f-f57489e329d1 fwd="104.251.99.162" dyno=web.1 connect=5ms service=29ms status=200 bytes=328 protocol=https
2017-12-18T20:22:45.085984+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/socket.io/?EIO=3&transport=polling&t=M1hIlxD&sid=tQ7s8lzd3CMcl7hiAAAA" host=tower-defense-mobx.herokuapp.com request_id=1bd1bace-6753-4665-908c-79367fa33f72 fwd="104.251.99.162" dyno=web.1 connect=0ms service=19ms status=503 bytes=0 protocol=https
2017-12-18T20:22:45.096164+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-12-18T20:22:45.101635+00:00 app[web.1]: npm ERR! tower-defense-web@0.1.0 start: `node ./bin/www`
2017-12-18T20:22:45.099523+00:00 app[web.1]: npm ERR! errno 1
2017-12-18T20:22:45.101637+00:00 app[web.1]: npm ERR! Exit status 1
2017-12-18T20:22:45.101638+00:00 app[web.1]: npm ERR! 
2017-12-18T20:22:45.101639+00:00 app[web.1]: npm ERR! Failed at the tower-defense-web@0.1.0 start script.
2017-12-18T20:22:45.101640+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2017-12-18T20:22:45.937209+00:00 app[web.1]: 
2017-12-18T20:22:45.937434+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-12-18T20:22:45.937576+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-12-18T20_22_45_105Z-debug.log

**Comment by danielmoniz** [comment]
Closing. This is old and very likely no longer exists.
